### Data
* What is data
* Types of Data
* Represent of Data

### Requirment for learn Data analysis
* Python
* Numpy
* Pandas
* Data Visulization

### Numpy:

* Numpy Stands for numerical python
* Numpy is python library for working with arrays,matrices,large and scietific calculations

### Numpy provides:

* Extension package to python for multi-dimenstional arrays
* It is closer to hardware 
* It provide more efficiency 
* It designed for scientif computation


### how to use numpy

* pip install numpy  => installation command
* we have to import numpy library
* It is pre-defined lib in jupyter

In [1]:
import numpy as np
np.__version__

'1.19.5'

In [2]:
# create numpy array
a=np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [3]:
type(a)

numpy.ndarray

* If data is 1D array => Vector
* If data is 2D array => matrices
* If data is 3D,4D,5D.. => Tensor

In [6]:
# 1D array
a=np.array([10,20,30,40,50])
print(a)
print("Type of a:",type(a))
print("Dimentions of a:",a.ndim)
print("shape of a:",a.shape)

[10 20 30 40 50]
Type of a: <class 'numpy.ndarray'>
Dimentions of a: 1
shape of a: (5,)


In [7]:
# 2D array => list->list
a=np.array([[10,20,30],[11,12,13],[23,45,67]])
print(a)
print("Type of a:",type(a))
print("Dimentions of a:",a.ndim)
print("shape of a:",a.shape)

[[10 20 30]
 [11 12 13]
 [23 45 67]]
Type of a: <class 'numpy.ndarray'>
Dimentions of a: 2
shape of a: (3, 3)


In [8]:
# 3D array => list->list->list
a=np.array([[[1,2,3],[4,5,6]],[[9,8,7],[5,4,3]],[[10,20,30],[50,60,70]]])
print(a)
print("Type of a:",type(a))
print("Dimentions of a:",a.ndim)
print("shape of a:",a.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 9  8  7]
  [ 5  4  3]]

 [[10 20 30]
  [50 60 70]]]
Type of a: <class 'numpy.ndarray'>
Dimentions of a: 3
shape of a: (3, 2, 3)


In [10]:
# difference b/w list and numpy

#normal list
l=range(1000)
%timeit [i**2 for i in l]

542 µs ± 10.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [14]:
l=np.arange(1000)
%timeit [i**2 for i in l]

521 µs ± 6.82 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [16]:
# linspace: linear space used for divide our data into equal parts
import numpy as np
l=np.linspace(1,10,5)
l


array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [19]:
# arange: used for take the data in a range of values
l=np.arange(10)
#l
l=np.arange(10,24) # start(included),end(excluded)
#l
l=np.arange(1,20,2) # start(included),end(excluded),step
l

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [20]:
# one's : it return one's in your array
l=np.ones((3,2))   # 3 rows, 2 columns
l

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
# zero's: it return zero's in your array
l=np.zeros((2,3))
#l
l=np.zeros((3,2))
l

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [28]:
# Identity matrix: eye (diagnal reprasents with one's)

l=np.eye(3)
l=np.eye(2)
l=np.eye(2,3)
l=np.eye(3,2)
l

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [29]:
# diagnal
l=np.diag([1,2,3,4,5])
l

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [31]:
# Task: extract the diagnal values in array
# output: 1,5,9
l=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(l)
np.diag(l)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 5, 9])

In [42]:
a=np.arange(9).reshape(3,3)
print(a)
np.diag(a)
np.flip(a)
np.fliplr(a)
np.flipud(a)
np.fliplr(a).diagonal()

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([2, 4, 6])