In [1]:
import numpy as np
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [5]:
print("size of array:",a.size)
print("shape of array:",a.shape)
print("dimention of array:",a.ndim)

size of array: 6
shape of array: (6,)
dimention of array: 1


In [7]:
a=np.array([1,2,3,4,5,6], ndmin=2)
print(a)
print("size of array:",a.size)
print("shape of array:",a.shape)
print("dimention of array:",a.ndim)

[[1 2 3 4 5 6]]
size of array: 6
shape of array: (1, 6)
dimention of array: 2


In [8]:
a=np.array([1,2,3,4,5,6], ndmin=3)
print(a)
print("size of array:",a.size)
print("shape of array:",a.shape)
print("dimention of array:",a.ndim)

[[[1 2 3 4 5 6]]]
size of array: 6
shape of array: (1, 1, 6)
dimention of array: 3


In [9]:
# We can create the no.of dimentions upto 32
a=np.array([1,2,3,4,5,6], ndmin=32)
print(a)
print("size of array:",a.size)
print("shape of array:",a.shape)
print("dimention of array:",a.ndim)

[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1 2 3 4 5 6]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
size of array: 6
shape of array: (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 6)
dimention of array: 32


In [10]:
a=np.array([1,2,3,4,5,6], ndmin=33)
print(a)
print("size of array:",a.size)
print("shape of array:",a.shape)
print("dimention of array:",a.ndim)

ValueError: ndmin bigger than allowable number of dimensions NPY_MAXDIMS (=32)

In [12]:
#data type
a=np.array([10,20,30,40])
print("data type of array:",a.dtype)

data type of array: int32


In [13]:
a=np.array([10.0,20.3,30.5,40.4])
print("data type of array:",a.dtype)

data type of array: float64


In [14]:
a=np.array([10,20.3,30,40.4])
print("data type of array:",a.dtype)

data type of array: float64


In [15]:
a=np.array(['a','b','c','d'])
print("data type of array:",a.dtype)

data type of array: <U1


In [16]:
a=np.array(['a',12,23.4,'s'])
print("data type of array:",a.dtype)

data type of array: <U4


In [17]:
a=np.array([True,False,False,True])
print("data type of array:",a.dtype)

data type of array: bool


In [18]:
a=np.array([2+3j,3+2j])
print("data type of array:",a.dtype)

data type of array: complex128


In [19]:
# data type conversions
a=np.array([1,2,3,4],dtype='float')
a

array([1., 2., 3., 4.])

In [20]:
a=np.array([1,2,3,4],dtype='complex')
a

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [21]:
a=np.array([1.2,2.3,3.4,4.6],dtype='int')
a

array([1, 2, 3, 4])

In [24]:
a=np.array([0,-1,3,4],dtype='bool')
a

array([False,  True,  True,  True])

### Access the data from numpy array

In [30]:
a=np.array([10,20,30,40,50,60,70,80,90])
a[3]
a[0:4]
a[:4]
a[5:]
a[0:7:2]

array([10, 30, 50, 70])

In [31]:
for i in a:
    print(i)

10
20
30
40
50
60
70
80
90


In [32]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
a.shape

(3, 4)

In [34]:
a[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
a[0:2,1:3]    #row,column

array([[2, 3],
       [6, 7]])

In [36]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
a[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [38]:
a[0:3:2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [48]:
# Random functions

#It return positive and negative values randomly
a=np.random.randn(6)
a

#It return integer value randomlly
a=np.random.randint(5)
a

#It return 5 positive numbers
a=np.random.rand(5)
a

array([0.11462963, 0.92753439, 0.5800056 , 0.01769614, 0.37613488])

In [59]:
# Reshape: it create a new shape of array

a=np.arange(9).reshape(3,3)
a
#a=np.arange(6).reshape(6,1)
#a=np.arange(6).reshape(2,3)
#a=np.arange(6).reshape(3,2)
a=np.arange(6).reshape(1,6)
a

a=np.arange(1,13).reshape(2,2,3)
a

a=np.arange(9).reshape(-1,1)
a

a=np.arange(9).reshape(1,-1)
a

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

### statstical and aggregations functions

In [67]:
a=np.array([10,20,30,40,50,60,70])
a.mean()
np.median(a)
np.std(a)
np.var(a)

400.0