In [1]:
import numpy as np
a=np.array([10,20,30,12,16,2,100])
a

array([ 10,  20,  30,  12,  16,   2, 100])

In [5]:
# statistics
# mean(),median(),std(),var()
# aggregate
# min(),max(),sum(),average()

np.min(a)
np.max(a)
np.sum(a)
np.average(a)

27.142857142857142

In [6]:
a=np.array([[1,3],[4,6]])
a

array([[1, 3],
       [4, 6]])

In [11]:
np.mean(a)
np.sum(a)
np.min(a)

1

In [15]:
#np.sum(a)
a.sum(axis=0)      # axis=0 means column
np.sum(a,axis=0)
np.sum(a,axis=1)   # axis=1 means row

array([ 4, 10])

In [17]:
np.mean(a,axis=0)
np.mean(a,axis=1)

array([2., 5.])

In [18]:
a=np.array([[10,20,30],[5,25,32],[12,100,24]])
a

array([[ 10,  20,  30],
       [  5,  25,  32],
       [ 12, 100,  24]])

In [20]:
print("min value in array:",np.min(a))
print("index of value in array:",a.argmin())

min value in array: 5
index of value in array: 3


In [22]:
print("max value in array:",np.max(a))
print("index of value in array:",a.argmax())

max value in array: 100
index of value in array: 7


In [26]:
# all and any
print("return the true when all elements as true:",np.all([True,True,True]))

print(np.all([True,True,False])) # return false if any one false in array
print(np.any([True,False,False]))  # return true if any one is true in array
print(np.any([False,False,False]))


return the true when all elements as true: True
False
True
False


In [30]:
a=np.zeros((5,5))
print(a)
print(np.any(a==0))
print(np.any(a!=0))
print(np.all(a==0))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
True
False
True


In [33]:
a=np.array([10e3])   # 10*10**3 =>10*1000
a

a=np.array([1e3,2e3,5e3])
a

array([1000., 2000., 5000.])

In [32]:
10**3

1000

### How to save the data

In [35]:
a=np.array([10,20,30,40])
np.savetxt('save2.txt',a)

In [36]:
s=np.loadtxt('save2.txt')
s

array([10., 20., 30., 40.])

In [43]:
# ravel()
a=np.array([[1,2,3],[4,5,6]])
print(a)
print("data type:",a.dtype)
print("data dimention:",a.ndim)

print("convert 2d to 1d:",a.ravel())

[[1 2 3]
 [4 5 6]]
data type: int32
data dimention: 2
convert 2d to 1d: [1 2 3 4 5 6]


In [44]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
a.T   # convert rows as columns

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [50]:
l1=[1,2,3,4]
l2=[10,20,30,40]
#l1+l2
#l1*l2

a1=np.array(l1)
a2=np.array(l2)

a1+a2
a1*a2
a1-a2

array([ -9, -18, -27, -36])

In [55]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
print(a1)
print(a2)
a1+a2
a1*a2

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[ 5, 12],
       [21, 32]])

### Numpy topics covered:

* What is data, types of data, represent of data
* how to create numpy array as 1d,2d,3d...ndimentional
* data types
* type conversion
* argange,linspace,eye,diag,arg
* how to access data using indexing
* statstics and aggregations
* save and load
* ravel, Transponce
* mathematics


### Pandas:

* Pandas is python library for creating datasets(Table)
* Pandas library is more efficience and effective in Data Science
* Pandas provide EDA(Exploratory Data Analysis)
* How to use pandas
    * install the pandas lib (pip install pandas)
    * import the pandas lib
    

### Types:
* Pandas is types
    * Series : it is nothing but 1d array
    * DataFrame: it is nothing but 2d array
    
### What is Data-set:
* Data set is nothing but table
<img src='table.png' height=50px weight=50px>


In [57]:
import numpy as np
import pandas as pd
pd.__version__

'1.2.5'

In [58]:
# list
l=[10,20,30,40,50,60,70,80]
s=pd.Series(l)
s

0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
dtype: int64

In [64]:
# numpy
a=np.array([100,200,300,400,500])
s=pd.Series(a)
s


a=np.array([100,200,300,400,500.90])
s=pd.Series(a)
s

a=np.array([100,200,300,400,500.90,"hai"])
s=pd.Series(a)
s

a=np.array([100,200,300,400,500.90,True])
s=pd.Series(a)
s

a=np.array(['100',200,300,400,500.90,True])
s=pd.Series(a)
s

0      100
1      200
2      300
3      400
4    500.9
5     True
dtype: object

In [65]:
type(s)

pandas.core.series.Series

In [66]:
s.dtype

dtype('O')

In [67]:
s.shape

(6,)

In [68]:
len(s)

6

In [69]:
min(s)

'100'

In [70]:
max(s)

'True'

In [78]:
# how to access the data from series
a=np.array([100,200,300,400,500,6000,True])
s=pd.Series(a)
s[0]
s[1:]
s[:3]
#min(s)
#min(s)
max(s)

6000