### Classification:

* Classfication is a categorical data or group the data
* Ex: yes or no, pass or fail, 1 or 0, mango or grape or orange

* two types:
    * Binary classfication
        * it have two values
        * ex: yes or no, pass or fail, 1 or 0,
    * Multi classfication
        * more than two values
        * 0 or 1 or 2, mango or grape or orange
  

### Logistic Regression:

* Logistic Regression is a supervised ML algorithm
* It is used for classfing the data in classfication
* Logistic regression use the sigmoid function 
* syntax: f(x)=1/1+e^(-x)

In [17]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
d=load_iris()
df=pd.DataFrame(d.data,columns=d.feature_names)
df['Target']=d.target
df.sample(10)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
126                6.2               2.8                4.8               1.8   
87                 6.3               2.3                4.4               1.3   
76                 6.8               2.8                4.8               1.4   
6                  4.6               3.4                1.4               0.3   
133                6.3               2.8                5.1               1.5   
0                  5.1               3.5                1.4               0.2   
3                  4.6               3.1                1.5               0.2   
43                 5.0               3.5                1.6               0.6   
55                 5.7               2.8                4.5               1.3   
121                5.6               2.8                4.9               2.0   

     Target  
126       2  
87        1  
76        1  
6         0  
133       2  
0         0  
3         0  
43        0  
55        1  
121       2

In [6]:
df['Target'].value_counts()

0    50
1    50
2    50
Name: Target, dtype: int64

In [8]:
df['Target'].unique()

array([0, 1, 2])

In [11]:
# select input and output values
x=df.drop('Target',axis=1)    # input
y=df['Target']                # output

In [13]:
# select the model
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model

LogisticRegression()

In [14]:
# Pass input and output values into model
model.fit(x,y)

C:\Users\Kanakamma\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [15]:
# find the accurary score
model.score(x,y)

0.9733333333333334

In [16]:
# predict the values
model.predict([[4.6,3.1,1.5,0.2]])

array([0])

In [18]:
model.predict([[6.2,2.8,4.8,1.8]])

array([2])

###  Use model selection

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [21]:
model.fit(x_train,y_train)

C:\Users\Kanakamma\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [24]:
from sklearn.metrics import accuracy_score
y_pred=model.predict(x_test)
#y_pred
accuracy_score(y_test,y_pred)*100

100.0

In [25]:
# data frame for acctual and predict
prd=pd.DataFrame({'acc':y_test,'pred':y_pred})
prd.sample(10)

acc  pred
145    2     2
64     1     1
55     1     1
118    2     2
31     0     0
30     0     0
143    2     2
104    2     2
18     0     0
108    2     2

### SVM => Support Vector Machine

* SVM is a supervised ML algoritham
* It use the boundary line for classfing the data
* SVM is used for Regression and Classfication
    * SVR => Support Vector Regression
    * SVC => Support Vector Classfication

In [27]:
# Task: apply the logistic Regression and SVM

# from sklearn.datasets import load_breast_cancer
# d=load_breast_cancer()
# d

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [30]:
from sklearn.datasets import load_iris
d=load_iris()
df=pd.DataFrame(d.data, columns=d.feature_names)
df['Target']=d.target
df.sample(10)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
86                6.7               3.1                4.7               1.5   
61                5.9               3.0                4.2               1.5   
3                 4.6               3.1                1.5               0.2   
50                7.0               3.2                4.7               1.4   
9                 4.9               3.1                1.5               0.1   
24                4.8               3.4                1.9               0.2   
81                5.5               2.4                3.7               1.0   
43                5.0               3.5                1.6               0.6   
93                5.0               2.3                3.3               1.0   
22                4.6               3.6                1.0               0.2   

    Target  
86       1  
61       1  
3        0  
50       1  
9        0  
24       0  
81       1  
43       0  
93       1  
22       0

In [31]:
# select input and output values
x=df.drop('Target',axis=1)    # input
y=df['Target']                # output

In [33]:
# select the model
from sklearn.svm import SVC
model=SVC()
model

SVC()

In [34]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [39]:
x_train.shape
y_test.shape

(30,)

In [35]:
# pass the data into model
model.fit(x_train,y_train)

SVC()

In [36]:
from sklearn.metrics import accuracy_score
y_pred=model.predict(x_test)
#y_pred
accuracy_score(y_test,y_pred)*100

100.0

In [37]:
# data frame for acctual and predict
prd=pd.DataFrame({'acc':y_test,'pred':y_pred})
prd.sample(10)

acc  pred
56     1     1
78     1     1
76     1     1
104    2     2
30     0     0
145    2     2
12     0     0
131    2     2
31     0     0
9      0     0

### Regression
* Mean Square Error
* Mean absolute Error
* Root mean square error

### Classfication

* Classfication report
* Confusion Matrix